name: Docker Image CI

on:
  push:
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: dockeraction # you'll use this in the next step
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            logzio/docker-collector-logs
          flavor: |
            latest=false
          # Docker tags based on the following events/attributes

      - name: Build and push amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          sbom: false
          provenance: false
          tags: ${{ steps.dockeraction.outputs.tags }}-amd
          labels: ${{ steps.dockeraction.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push amd64 latest
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          sbom: false
          provenance: false
          tags: logzio/docker-collector-logs:latest-amd
          labels: ${{ steps.dockeraction.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push arm64 latest
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.arm
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          sbom: false
          provenance: false
          tags: logzio/docker-collector-logs:latest-arm
          labels: ${{ steps.dockeraction.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.arm
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          sbom: false
          provenance: false
          tags: ${{ steps.dockeraction.outputs.tags }}-arm
          labels: ${{ steps.dockeraction.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create manifest version
        if: github.event_name != 'pull_request'
        run: |
          docker manifest create ${{ steps.dockeraction.outputs.tags }} \
            --amend ${{ steps.dockeraction.outputs.tags }}-arm \
            --amend ${{ steps.dockeraction.outputs.tags }}-amd

      - name: Create manifest latest
        if: github.event_name != 'pull_request'
        run: |
          docker manifest create logzio/docker-collector-logs:latest \
            --amend logzio/docker-collector-logs:latest-arm \
            --amend logzio/docker-collector-logs:latest-amd

      - name: Push manifest latest
        if: github.event_name != 'pull_request'
        run: |
          docker manifest push logzio/docker-collector-logs:latest
          
      - name: Push manifest version
        if: github.event_name != 'pull_request'
        run: |
          docker manifest push ${{ steps.dockeraction.outputs.tags }}
